basic_app/urls.py
from django.urls import path
from basic_app.views import SchoolListView, SchoolDetailView

app_name = 'basic_app'

urlpatterns = [
    path('schools/', SchoolListView.as_view(), name='school_list'),
    path('schools/<int:pk>', SchoolDetailView.as_view(), name='school_detail'),
]

cbvproject/urls.py
from django.contrib import admin
from django.urls import path, include
from basic_app.views import IndexView

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('admin/', admin.site.urls),
    path('basic_app/', include('basic_app.urls')),
]

basic_app/models.py
from django.db import models


class School(models.Model):
    name = models.CharField(max_length=255)
    principal = models.CharField(max_length=100)
    location = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Student(models.Model):
    school = models.ForeignKey(
        School, related_name='students', on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    email = models.EmailField()

    def __str__(self):
        return self.name

basic_app/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, ListView, DetailView
from basic_app.models import School


class IndexView(TemplateView):
    template_name = 'basic_app/index.html'


class SchoolListView(ListView):
    context_object_name = 'schools'
    model = School


class SchoolDetailView(DetailView):
    context_object_name = 'school'
    model = School

basic_app/templates/base.html
<!doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- Bootstrap CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">

  <title>CBV Example</title>
</head>

<body>

  <nav class="container navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'index' %}">CBV</a>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'basic_app:school_list' %}">Schools</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Admin</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

  <div class="container">
    {% block content %}
    {% endblock content %}
  </div>

  <!-- Option 1: Bootstrap Bundle with Popper -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0"
    crossorigin="anonymous"></script>

</body>

</html>

basic_app/templates/basic_app/index.html
{% extends "base.html" %}

{% block content %}
    <h1 class="text-center alert">Home page</h1>
{% endblock content %}

basic_app/templates/basic_app/school_detail.html
{% extends "base.html" %}
{% block content%}

<h2 class="text-center alert">School Detail</h2>


Name: <h4>{{school.name}}</h4>
Principal: <p>{{school.principal}}</p>
Location: <p>{{school.location}}</p>

<h3>Students List of this School</h3>

<ol>
    {% for student in school.students.all %}
    <li>{{student.name}} : {{student.email}}</li>
    {% endfor %}
</ol>

{% endblock content %}

basic_app/templates/basic_app/school_list.html
{% extends "base.html" %}
{% block content%}

<h3 class="text-center alert">Schools List</h3>

<ol>
    {% for school in schools %}
    <li>
        <a href="{% url 'basic_app:school_detail' pk=school.id %}">{{school.name}}</a>
    </li>
    {% endfor %}
</ol>

{% endblock content %}